language: java
jdk:
  - oraclejdk8

# Notify development list when needed
notifications:
 recipients:
   - exkazuu@gmail.com
   - nnujabok@gmail.com
   - ohata@sakailab.info
   - matsuzawa@si.aoyama.ac.jp
 email:
   on_success: change
   on_failure: always
